//
//  Disclaimers.swift
//  OLMoE.swift
//
//  Created by Stanley Jovel on 11/14/24.
//


import Foundation

protocol Disclaimer {
    var title: String { get }
    var text: String { get }
    var headerTextContent: [HeaderTextPair] { get }
    var buttonText: String { get }
}

struct Disclaimers {

    struct FullDisclaimer: Disclaimer {
        let title = "Disclaimer"
        let text = ""
        let buttonText = "Agree"
        let headerTextContent = [
            HeaderTextPair(
                header: "Acceptance",
                text: """
                By pressing the “Agree” button below, I agree to Ai2’s [Terms of Use](https://allenai.org/terms) and [Responsible Use Guidelines](https://allenai.org/responsible-use) for this OlmoE App. 
                """),
            HeaderTextPair(
                header: "Limitations",
                text: """
                Large pretrained language models, such as OLMoE, are trained on data sourced from the internet. Ai2 uses several strategies to mitigate these behaviors for the benefit of the general public, but model outputs in the OLMoE App will still contain biases, toxic content, or harmful language. These undesirable results have a legitimate research purpose, however, especially for researchers investigating the sources of bias, toxicity, and harmful language generated by LLMs.
                """),
            HeaderTextPair(
                header: "Privacy and Data Collection",
                text: """
                Your data is only shared when you choose to share your conversation. Once you share, you will not have the ability to delete the data you shared. It will be stored and used for future research and educational purposes in the public interest, consistent with Ai2’s mission as a 501(c)(3) nonprofit organization. All retained prompt history and user interaction data you choose to share may be shared outside of Ai2, as permitted by applicable law and Ai2’s policies. Please use your discretion and best judgment when accessing and using the OMLoE app. **NEVER** submit any personal, sensitive, or confidential information in your use of the app.
                """)
        ]
    }

    struct ShareDisclaimer: Disclaimer {
        let title = "Sharing Consent"
        let text = """
            When sharing a link to a conversation, you are consenting to share your messages with Ai2 and your conversation will be transmitted and stored on Ai2's servers. Please do not share PII (personally identifiable information) or any other sensitive information in your conversation.

            Once you select “Share” below, your conversation and related interaction data will be retained by Ai2 as described in our [Terms of Use](https://allenai.org/terms/2024-09-25) and [Privacy Policy](https://allenai.org/privacy-policy). By sharing, you agree to allow Ai2 to collect this interaction data for scientific research and educational purposes and to develop or improve this app as well as  the models and underlying technology presented in this app. If you do not want to share your interaction data with Ai2, please press “Cancel” to cancel sharing.
            """
        let buttonText = "Share"
        let headerTextContent = [HeaderTextPair]()
    }
}
