AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 Logging Lambda Function

Parameters:
  BucketName:
    Type: String
  S3LogPrefix:
    Type: String
  S3SharePrefix:
    Type: String
  CertificateAsBytes:
    Type: String
  AppId:
    Type: String
  HmacShaKey:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - dev
      - prod
      - test
    Default: prod
  MaxRequestSizeBytes:
    Type: Number
    Default: 51200 # 50KB

Resources:
  OlmoeAttestS3LoggingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: olmoe-attest-s3-share-logging-function
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          S3_LOG_PREFIX: !Ref S3LogPrefix
          S3_SHARE_PREFIX: !Ref S3SharePrefix
          CERTIFICATE_AS_BYTES: !Ref CertificateAsBytes
          APP_ID: !Ref AppId
          HMAC_SHA_KEY: !Ref HmacShaKey
          ENV: !Ref Env
          MAX_REQUEST_SIZE_BYTES: !Ref MaxRequestSizeBytes
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BucketName

Outputs:
  OlmoeAttestS3LoggingFunction:
    Description: "S3 Logging Lambda Function ARN"
    Value: !GetAtt OlmoeAttestS3LoggingFunction.Arn